### ISSUE TITLE
lsa commit give runtime error!

### ISSUE THREAD

**Issue by HassanZareie** [SharifAIChallenge/AIC20-Client-Java#2]
Error: Can not recieve server's message.
java.lang.NullPointerException
	at Client.Model.Path.<init>(Path.java:27)
	at Client.Model.Game.setOrderOfUnitsPaths(Game.java:912)
	at Client.Model.Game.handleTurnMessage(Game.java:956)
	at Client.Controller.handleTurnMessage(Controller.java:143)
	at Client.Controller.handleMessage(Controller.java:114)
	at Client.Network.doReceive(Network.java:129)
	at Client.Network.lambda$startReceiving$0(Network.java:118)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by taslimisina** [comment]
Fixed
